baseURL: 'https://statistico.io/'
languageCode: 'en-us'
title: 'Statistico'
googleAnalytics: 'G-12XDRNF6YQ'

params:
  banner:
    video: '/video/banner-video.mov'
  favicon: '/img/favicon.ico'
  logo:
    ball: '/img/statistico-logo-ball.png'
    textBlue: '/img/statistico-logo-text.png'
    textWhite: '/img/statistico-logo-text-white.png'
  howItWorks:
    exchangeMobile: '/img/exchange-mobile.png'
    statisticoMobile: '/img/statistico-mobile.png'
    statisticoTablet: '/img/statistico-tablet.png'
