version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  hugo: circleci/hugo@1.3.0

jobs:
  build-and-test:
    executor: hugo/default
    steps:
      - checkout
      - hugo/hugo-build
      - hugo/html-proofer:
          check-favicon: true
          check-img-http: true
          error-sort: ':path'
          path: public
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - attach_workspace:
          at: public
      - aws-cli/setup
      - run:
          name: Deploy artifacts
          command: aws s3 sync public/* s3://statistico.io --acl public-read
#      - run:
#          name: Invalidate CloudFront Cache
#          command: |
#            aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION} --paths "/*"

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          context: aws
          requires:
            - build-and-test
#          filters:
#            branches:
#              only: master
